# caps lock = esc
# caps + h/j/k/l works as arrow keys
# caps + d/u = pg down/pg up
# need to sudo systemctl restart keyd after changes
[ids]
*

[main]
capslock = overload(nav, esc)

[nav]
h = left
j = f13 
k = f14 
l = right
d = pagedown
u = pageup
